### ISSUE TITLE
Decode into instance of struct of an interface type

### ISSUE THREAD

**Issue by Codebreaker101** [vmihailenco/msgpack#272]
When decoding into an struct with a field of type `interface{}`, it decodes into `map[string]interface{}`, despite the fact that the field has an instance of a concrete type. One of the solutions is to register a type, but this must be done on the sender and the receiver side. I'm wondering, is there an alternative solution to this problem? 

https://play.golang.org/p/iFid5_b-Hda

``` go
package main

import (
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
)

type Baz struct {
	ID        int64
	IsChicken bool
}

type Foo struct {
	Name string
	Type interface{}
}

func main() {
	foo := Foo{
		Name: "Heihei",
		Type: Baz{
			ID:        88282,
			IsChicken: true,
		},
	}

	bytes, err := msgpack.Marshal(foo)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%T\n", foo.Type)

	// ===================================

	foo3 := Foo{
		Type: &Baz{},
	}
	if err := msgpack.Unmarshal(bytes, &foo3); err != nil {
		panic(err)
	}
	fmt.Printf("%T\n", foo3.Type) // should be of type Baz
}


```

**Comment by freeliver** [comment]
use rawmessage can work
but msgpack v5 not support nested struct like Struct{ field1:..., field:&msgpack.RawMessage}
fixed by https://github.com/vmihailenco/msgpack/pull/278

**Comment by vmihailenco** [comment]
Should be fixed in v5.0.0-beta.5

**Comment by tmm1** [comment]
I'm still having this same issue.

>panic: reflect.Set: value of type map[string]interface {} is not assignable to type myInterfaceName

Instead of a panic, would it be possible to return a real error like encoding/json does?

	err := json.Unmarshal(data, &tmp)
	if je, ok := err.(*json.UnmarshalTypeError); ok && je.Type.String() == "myInterfaceName" {
